package icu.repsaj.android.mytrivia.data.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import icu.repsaj.android.mytrivia.model.HistoryItem
import java.util.Date

/**
 * Represents a game history item entity in the database.
 *
 * @property id The unique identifier of the game history item, which is auto-generated by the database.
 * @property category The category of the game.
 * @property date The date when the game was played.
 * @property score The score achieved in the game.
 */
@Entity(tableName = "game_history")
data class DbGameHistoryItem(
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0,
    var category: String = "",
    var date: Date,
    var score: Int = 0
)

/**
 * Converts a database entity [DbGameHistoryItem] into its domain representation [HistoryItem].
 *
 * @return A [HistoryItem] object with properties corresponding to the [DbGameHistoryItem].
 */
fun DbGameHistoryItem.asDomainObject(): HistoryItem {
    return HistoryItem(
        id = this.id,
        category = this.category,
        date = this.date,
        score = this.score
    )
}

/**
 * Converts a domain object [HistoryItem] into a database entity [DbGameHistoryItem].
 *
 * If the [HistoryItem.id] is null, it defaults to 0 for the database entity.
 *
 * @return A [DbGameHistoryItem] object with properties corresponding to the [HistoryItem].
 */
fun HistoryItem.asDbEntity(): DbGameHistoryItem {
    return DbGameHistoryItem(
        id = this.id ?: 0,
        category = this.category,
        date = this.date,
        score = this.score
    )
}

/**
 * Extension function on List<[DbGameHistoryItem]> to convert a list of database entities into a list of domain objects.
 *
 * @return A list of [HistoryItem] objects corresponding to the [DbGameHistoryItem] objects in the list.
 */
fun List<DbGameHistoryItem>.asDomainObjects(): List<HistoryItem> {
    return this.map { it.asDomainObject() }
}
